validduration: 120
alias: jwtiscool
keyFile: jwtiscool.jks
password: jwtiscool
spring:
  datasource:
    password: sapient
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
